forum/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('discussions', 'DiscussionsController');

Route::resource('discussions/{discussion}/replies', 'RepliesController');

Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@reply')->name('discussions.best-reply');

Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');

forum/app/Discussion.php
<?php

namespace App;

use App\User;
use App\Channel;
use Illuminate\Database\Eloquent\Model;
use App\Notifications\ReplyMarkedAsBestReply;

class Discussion extends Model
{
    protected $fillable = ['title', 'content', 'slug', 'channel_id', 'user_id', 'best_reply_id'];

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function bestReply()
    {
        return $this->belongsTo(Reply::class, 'best_reply_id');
    }

    public function markAsBestReply(Reply $reply)
    {
        $this->update([
            'best_reply_id' => $reply->id
        ]);

        if($reply->user->id === $this->author->id) {
            return;
        }

        $reply->user->notify(new ReplyMarkedAsBestReply($reply->discussion));
    }

    public function scopeFilterByChannels($builder)
    {
        if(request()->query('channel')) {
            $channel = Channel::where('slug', request()->query('channel'))->first();

            if($channel) {
                $builder->where('channel_id', $channel->id);
            }

            return $builder;
        }

        return $builder;
    }
}

forum/app/Http/Controllers/DiscussionsController.php
<?php

namespace App\Http\Controllers;

use App\Reply;
use App\Discussion;
use Illuminate\Http\Request;
use App\Http\Requests\Discussions\CreateDiscussionRequest;

class DiscussionsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified'])->only(['create', 'store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('discussions.index', [
            'discussions' => Discussion::filterByChannels()->paginate(3)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDiscussionRequest $request)
    {
        auth()->user()->discussions()->create([
            'title' => $request->title,
            'slug' => str_slug($request->title),
            'content' => $request->content,
            'channel_id' => $request->channel
        ]);

        session()->flash('success', 'Discussion posted.');

        return redirect()->route('discussions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Discussion $discussion)
    {
        return view('discussions.show', ['discussion' => $discussion]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function reply(Discussion $discussion, Reply $reply)
    {
        $discussion->markAsBestReply($reply);

        session()->flash('success', 'Marked as best reply.');

        return redirect()->back();
    }
}

forum/resources/views/discussions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Add Discussion</div>

    <div class="card-body">
        @include('partials.errors')

        <form action="{{ route('discussions.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="">
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <input id="content" type="hidden" name="content">
                <trix-editor input="content"></trix-editor>
            </div>
            <div class="form-group">
                <label for="channel">Channel</label>
                <select name="channel" id="channel" class="form-control">
                    @foreach($channels as $channel)
                    <option value="{{ $channel->id }}">{{ $channel->name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-success">Create Discussion</button>
        </form>
    </div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

forum/resources/views/discussions/index.blade.php
@extends('layouts.app')

@section('content')
@if($discussions->count() > 0)
@foreach($discussions as $discussion)
<div class="card mb-4">
    @include('partials.discussion-header')

    <div class="card-body">
        <h5 class="text-center"><strong>{{ $discussion->title }}</strong></h5>
    </div>
</div>
@endforeach
@else
<h3 class="my-5">No discussions yet.</h3>
@endif

{{ $discussions->appends(['channel' => request()->query('channel')])->links() }}
@endsection

forum/resources/views/discussions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card mb-5">
    @include('partials.discussion-header')

    <div class="card-body">
        <h5 class="text-center"><strong>{{ $discussion->title }}</strong></h5>

        <hr>

        {!! $discussion->content !!}

        @if($discussion->bestReply)
        <div class="card bg-success text-white mt-4 mb-2">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <img src="{{ Gravatar::src($discussion->bestReply->user->email)}}" width="30px"
                            style="border-radius: 50%" alt="">
                        <span class="ml-2"><strong>{{ $discussion->bestReply->user->name }}</strong></span>
                    </div>
                    <div>
                        <strong>Best reply</strong>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {!! $discussion->bestReply->reply !!}
            </div>
        </div>
        @endif
    </div>
</div>

@foreach($discussion->replies()->paginate(3) as $reply)
<div class="card mb-2">
    <div class="card-header">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <img src="{{ Gravatar::src($reply->user->email) }}" width="30px" style="border-radius: 50%;" alt="">
                <span class="ml-2">{{ $reply->user->name }}</span>
            </div>

            @auth
            @if(auth()->user()->id === $discussion->user_id)
            <div>
                <form
                    action="{{ route('discussions.best-reply', ['discussion' => $discussion->slug, 'reply' => $reply->id]) }}"
                    method="POST">
                    @csrf
                    <button type="submit" class="btn btn-primary btn-sm">Mark as best reply</button>
                </form>
            </div>
            @endif
            @endauth
        </div>
    </div>
    <div class="card-body">
        {!! $reply->reply !!}
    </div>
</div>
@endforeach
<div class="mb-5">
    {{ $discussion->replies()->paginate(3)->links() }}
</div>

<div class="card">
    <div class="card-header">
        Add a reply
    </div>
    <div class="card-body">
        @auth

        @include('partials.errors')

        <form action="{{ route('replies.store', $discussion->slug) }}" method="POST">
            @csrf
            <input id="reply" type="hidden" name="reply">
            <trix-editor input="reply"></trix-editor>

            <button type="submit" class="btn btn-success btn-sm mt-2">Add reply</button>
        </form>

        @else

        <a href="{{ route('login') }}" class="btn btn-info">Sign in to add a reply</a>

        @endauth
    </div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection